#!/bin/sh
#
# S99-showing-picture-service 
#
#### init script for signage on pi2
##
## S99showpng - init script 
## This file contains the contents of signage-on-pi.
##
## Copyright (C) 2018 Shintaro Fujiwara
##
## This library is free software; you can redistribute it and/or
## modify it under the terms of the GNU Lesser General Public
## License as published by the Free Software Foundation; either
## version 2.1 of the License, or (at your option) any later version.
##
## This library is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public
## License along with this library; if not, write to the Free Software
## Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
##  02110-1301 USA
####

PATH=/sbin:/bin:/usr/bin
DAEMON="/usr/bin/show-png-oneshot-daemon"
test -f ${DAEMON} || exit 0

startdaemon(){
  echo -n "Starting ${DAEMON}: "
  start-stop-daemon -b --start --quiet --exec ${DAEMON}
  echo "${DAEMON} started."
}

stopdaemon(){
  echo -n "Stopping ${DAEMON}: "
  start-stop-daemon --stop --quiet --exec ${DAEMON}
  echo "${DAEMON} stopped."
}

case "$1" in
  start)
      startdaemon
      ;;
  stop)
      stopdaemon
      ;;
  force-reload)
      stopdaemon
      startdaemon
      ;;
  restart)
      stopdaemon
      startdaemon
      ;;
  *)
      echo "Usage: $0 { start | stop | restart}" >&2
      exit 1
      ;;
esac
